# Generated by Django 5.0.1 on 2024-02-08 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_category_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='products',
        ),
    ]
